### Entropy


Intuitively, we can think of **entropy** as the measure of disorder in a system. 

This set, $S$, for example, is very disordered:

<img src="https://www.evernote.com/l/AAEZbuSslJRCwKxfZaSIBJaIZqcQ-mTe9RQB/image.png" width=400px>


Let us consider the elements of $S$ that have a black border.

In [1]:
%run items.py

In [2]:
items

[{'form': 'square', 'letter': 'E', 'color': 'blue', 'border': False},
 {'form': 'circle', 'letter': 'A', 'color': 'red', 'border': True},
 {'form': 'circle', 'letter': 'B', 'color': 'green', 'border': False},
 {'form': 'diamond', 'letter': 'E', 'color': 'red', 'border': True},
 {'form': 'diamond', 'letter': 'E', 'color': 'red', 'border': True},
 {'form': 'diamond', 'letter': 'C', 'color': 'blue', 'border': False},
 {'form': 'square', 'letter': 'A', 'color': 'green', 'border': False},
 {'form': 'diamond', 'letter': 'D', 'color': 'green', 'border': True},
 {'form': 'star', 'letter': 'C', 'color': 'silver', 'border': True},
 {'form': 'square', 'letter': 'C', 'color': 'silver', 'border': False},
 {'form': 'circle', 'letter': 'B', 'color': 'green', 'border': False},
 {'form': 'circle', 'letter': 'A', 'color': 'red', 'border': True},
 {'form': 'square', 'letter': 'A', 'color': 'green', 'border': False},
 {'form': 'circle', 'letter': 'D', 'color': 'green', 'border': True},
 {'form': 'star', '

In [3]:
import numpy as np
import pandas as pd

from IPython.display import display

items_df = pd.DataFrame(items)
items_df

border   color     form letter
0    False    blue   square      E
1     True     red   circle      A
2    False   green   circle      B
3     True     red  diamond      E
4     True     red  diamond      E
5    False    blue  diamond      C
6    False   green   square      A
7     True   green  diamond      D
8     True  silver     star      C
9    False  silver   square      C
10   False   green   circle      B
11    True     red   circle      A
12   False   green   square      A
13    True   green   circle      D
14    True    blue     star      B
15    True    blue   circle      B
16   False    blue   square      E
17    True     red  diamond      E
18    True    blue     star      B
19   False  purple   square      C
20   False  silver   square      C

## Information Entropy


We can measure the disorder in $S$ relative to any attribute of an element using the Shannon Information **Entropy**

$$H(S) = -p_1\log_2p_1 + \dots + -p_n\log_2p_n$$




Here, each $p_i$ is a measure of the proportion of the set represented by each class for a given attribute. If we are looking at the color of our shapes, this would be five classes: 

In [11]:
set(items_df.color)

{'blue', 'green', 'purple', 'red', 'silver'}

In [4]:
items_df.color.unique()

array(['blue', 'red', 'green', 'silver', 'purple'], dtype=object)

We can use Python to calculate the entropy

In [5]:
def class_entropy(proportion):
    return -proportion*np.log2(proportion)

In [6]:
def entropy(proportions):
    class_entropies = [class_entropy(proportion) 
                       for proportion in proportions]
    return sum(class_entropies)

### Measure The Entropy of the color of $S$ 

In [7]:
n = items_df.color.count()
n

21

In [8]:
p_red = (items_df.color == 'red').sum()/n
p_blue = (items_df.color == 'blue').sum()/n
p_green = (items_df.color == 'green').sum()/n
p_silver = (items_df.color == 'silver').sum()/n
p_purple = (items_df.color == 'purple').sum()/n

S_proportions = [p_red, p_blue, p_green, p_silver, p_purple]
S_proportions

[0.23809523809523808,
 0.2857142857142857,
 0.2857142857142857,
 0.14285714285714285,
 0.047619047619047616]

In [9]:
sum(S_proportions)

1.0

In [10]:
entropy(S_proportions)

2.1359327568142765

## To Do

Write a method that calculates the class proportions for a given dataframe and feature.


In [12]:
3*True

3

In [14]:
np.array([True, False]) + np.array([False, True]) 

array([ True,  True], dtype=bool)

In [18]:
def class_proportions(series):
    classes = series.unique()
    total_count = series.count()
    counts = np.array([(series == cls).sum() for cls in classes])
    return counts/total_count

In [19]:
class_proportions(items_df.color)

array([ 0.28571429,  0.23809524,  0.28571429,  0.14285714,  0.04761905])

In [20]:
class_proportions(items_df.border)

array([ 0.47619048,  0.52380952])

In [21]:
def entropy(series):
    proportions = class_proportions(series)
    class_entropies = [class_entropy(proportion) 
                       for proportion in proportions]
    return sum(class_entropies)

Use this method to calculate the Entropy with respect to each attribute of $S$

In [22]:
display("color:  {}".format(class_proportions(items_df.color)))
display("form:   {}".format(class_proportions(items_df.form)))
display("letter: {}".format(class_proportions(items_df.letter)))
display("border: {}".format(class_proportions(items_df.border)))

'color:  [ 0.28571429  0.23809524  0.28571429  0.14285714  0.04761905]'

'form:   [ 0.33333333  0.28571429  0.23809524  0.14285714]'

'letter: [ 0.23809524  0.19047619  0.23809524  0.23809524  0.0952381 ]'

'border: [ 0.47619048  0.52380952]'

In [23]:
display("color:  {}".format(entropy(items_df.color)))
display("form:   {}".format(entropy(items_df.form)))
display("letter: {}".format(entropy(items_df.letter)))
display("border: {}".format(entropy(items_df.border)))

'color:  2.1359327568142765'

'form:   1.938708497286834'

'letter: 2.2576068788115964'

'border: 0.998363672593813'

## The Decision Tree

Decision Trees are supervised learning models typically split into classification trees and regression trees. For the rest of this lesson, we will focus on classification trees. 

We will work through the ID3 algorithm for learning a decision tree from a set of labeled data. 

#### Labeled Data

For our purposes, let us assume that the feature `border` is our label. We will be seeking a decision tree that makes splits in order to develop a model for identifying which items will have a border. 

In [26]:
features = items_df.drop('border', axis=1)
target = items_df.border

In [27]:
class_proportions(target)

array([ 0.47619048,  0.52380952])

In [28]:
entropy(target)

0.99836367259381298

### Three Partitioning Schemes

We can start by separating the elements based upon their attributes. Here are three different ways to do that:


![](img/entropy_3.png)

### Identify the Best Split

In order to proceed, we will need to identify which of these ways of separating is best? We can use the measure of entropy to do this!


#### Split by Form

In [29]:
features_square_df = features[features.form == 'square']
features_circle_df = features[features.form == 'circle']
features_diamond_df = features[features.form == 'diamond']
features_star_df = features[features.form == 'star']

target_square_df = target[features.form == 'square']
target_circle_df = target[features.form == 'circle']
target_diamond_df = target[features.form == 'diamond']
target_star_df = target[features.form == 'star']

display(pd.merge(features_square_df, pd.DataFrame(target_square_df), left_index=True, right_index=True))
display(pd.merge(features_circle_df, pd.DataFrame(target_circle_df), left_index=True, right_index=True))
display(pd.merge(features_diamond_df, pd.DataFrame(target_diamond_df), left_index=True, right_index=True))
display(pd.merge(features_star_df, pd.DataFrame(target_star_df), left_index=True, right_index=True))


color    form letter  border
0     blue  square      E   False
6    green  square      A   False
9   silver  square      C   False
12   green  square      A   False
16    blue  square      E   False
19  purple  square      C   False
20  silver  square      C   False

color    form letter  border
1     red  circle      A    True
2   green  circle      B   False
10  green  circle      B   False
11    red  circle      A    True
13  green  circle      D    True
15   blue  circle      B    True

color     form letter  border
3     red  diamond      E    True
4     red  diamond      E    True
5    blue  diamond      C   False
7   green  diamond      D    True
17    red  diamond      E    True

color  form letter  border
8   silver  star      C    True
14    blue  star      B    True
18    blue  star      B    True

To assess this split, we will be seeking the entropy associated with each subset as a proportion of the total set.

$$H_T = q_{\text{square}}H(S_{\text{square}}) + 
        q_{\text{circle}}H(S_{\text{circle}}) + 
        q_{\text{diamond}}H(S_{\text{diamond}}) + 
        q_{\text{star}}H(S_{\text{star}})
$$

Here each $q_i$ represents the **weight**, the proportion of the total each subset is

$$q_i = \frac{\text{count}(S_i)}{\text{count}(S_T)}$$

In [30]:
q_square = features_square_df.form.count()/features.form.count()
q_circle = features_circle_df.form.count()/features.form.count()
q_diamond = features_diamond_df.form.count()/features.form.count()
q_star = features_star_df.form.count()/features.form.count()

### Total Entropy When Split by Form

##### Calculate the weights of each class of our target

In [32]:
display("squares:  {}".format(class_proportions(target_square_df)))
display("circles:   {}".format(class_proportions(target_circle_df)))
display("diamond: {}".format(class_proportions(target_diamond_df)))
display("star: {}".format(class_proportions(target_star_df)))

'squares:  [ 1.]'

'circles:   [ 0.66666667  0.33333333]'

'diamond: [ 0.8  0.2]'

'star: [ 1.]'

##### Find the entropy for these proportions

In [33]:
display("square:  {}".format(entropy(target_square_df)))
display("circle:   {}".format(entropy(target_circle_df)))
display("diamond: {}".format(entropy(target_diamond_df)))
display("star: {}".format(entropy(target_star_df)))

'square:  0.0'

'circle:   0.9182958340544896'

'diamond: 0.7219280948873623'

'star: 0.0'

In [34]:
H_square_border = entropy(target_square_df)
H_circle_border = entropy(target_circle_df)
H_diamond_border = entropy(target_diamond_df)
H_star_border = entropy(target_star_df)

##### Sum the weighted Entropy

In [35]:
(q_square*H_square_border + 
 q_circle*H_circle_border + 
 q_diamond*H_diamond_border + 
 q_star*H_star_border)

0.43425787994113085

### Write a function to do this for a split on any feature

In [36]:
def entropy_on_split(dataframe, target, feature, debug=False):
    
    # split on feature
    unique_classes = dataframe[feature].unique()    
    target_subsets = [
        target[dataframe[feature] == unique_class] 
        for unique_class in unique_classes
    ]
        
    # calculate subset weights
    total = target.count()
    weights = [
        target_subset.count()/total
        for target_subset in target_subsets
    ]
    
    # calculate entropies
    entropies = [
        entropy(target_subset)
        for target_subset in target_subsets
    ]
        
    # return weighted entropy
    return sum(weight*entropy for weight, entropy in zip(weights, entropies))

In [37]:
entropy_on_split(features, target, 'form')

0.43425787994113085

In [38]:
entropy_on_split(features, target, 'color')

0.67926964316620975

In [39]:
entropy_on_split(features, target, 'letter')

0.82472125804683316

### Write a function to Identify the Best Split

In [40]:
def find_best_split(features, target):
    feature_labels = features.columns
    entropies = [
        entropy_on_split(features, target, feature_label)
        for feature_label in feature_labels
    ]
    
    best_index = np.argmin(entropies)
    return feature_labels[best_index]

In [41]:
find_best_split(features, target)

'form'

## Representing the Tree

The ability to find a best split will only work at a single node. In order to build a complete machine learning model, we are going to need to use this method to build an entire decision tree.

We have this so far:

<img src="https://www.evernote.com/l/AAFzXwQ0IPVAcYpRMWQuaQCf0NvtOC4mz0sB/image.png" width=400px>

But what about the rest of the tree? We want to split like this:

<img src="https://www.evernote.com/l/AAHMTpccFvtOjYGojh7sZ97oDC6-bRNAPe4B/image.png" width=400px>

<img src="https://www.evernote.com/l/AAGE0WSC6F5AzLCUX-A3cwXrQULf_uFRyFYB/image.png" width=400px>

In order to represent this using Python, we will define a `tree` to be one of these:

- `True`
- `False`
- a tuple `(attribute, subtree)`

For example, consider the tree representing green circles containing the letter 'B'.

We can represent this trivially as:

In [42]:
green_circle_B_tree = False

or the tree representing green circles containing the letter 'D':

In [43]:
green_circle_D_tree = True

From there, consider the tree representing green circles:

<img src="https://www.evernote.com/l/AAEbErEwS7hETI2gNXzkaetSXntpxeGKjSoB/image.png" width=200px>

In [44]:
green_circle_tree = ('letter', {'B' : False, 'D' : True})

We might gradually work our way up from there and represent our entire tree as

In [45]:
tree = ('form', {'square': False,
                 'circle': 
                           ('color', {'green': 
                                               ('letter', {'B' : False, 
                                                           'D' : True}),
                                      'red': True,
                                      'blue': True}),
                 'diamond': 
                            ('letter', {'C': False,
                                        'D': True,
                                        'E': True}),
                 'star': True})

### Use a tree to classifiy an input

Suppose we had a new element and we wish to no whether or not is has a border. For example, we may be given the following element:

    {'form': 'circle', 'letter': 'C', 'color': 'red'}

We are going to need to build a classification function to use our tree to classify this input.

In [46]:
def classify(tree, element):
    if tree in [True, False]:
        return tree
    
    attribute, subtree_dictionary = tree
    
    subtree_key = element.get(attribute)
    
    if subtree_key not in subtree_dictionary:
        subtree_key = None
    
    subtree = subtree_dictionary[subtree_key]
    
    return classify(subtree, element)

In [47]:
classify(tree, {'form': 'circle', 'letter': 'C', 'color': 'red'})

True

But what if we pass an element that is ambiguous, for example

    {'form': 'circle', 'letter': 'C', 'color': 'green'}

In [48]:
classify(tree, {'form': 'circle', 'letter': 'C', 'color': 'green'})

KeyError: None

### To Handle this, we will redefine our Tree

We will add a `None` key that returns the most common class.

In [49]:
tree = ('form', {'square': False,
                 'circle': 
                           ('color', {'green': 
                                               ('letter', {'B' : False, 
                                                           'D' : True,
                                                           None: False}),
                                      'red': True,
                                      'blue': True,
                                      None : True}),
                 'diamond': 
                            ('letter', {'C': False,
                                        'D': True,
                                        'E': True,
                                        None: True}),
                 'star': True,
                 None: True})

In [50]:
def classify(tree, element):
    if tree in [True, False]:
        return tree
    
    attribute, subtree_dictionary = tree
    
    subtree_key = element.get(attribute)
    
    if subtree_key not in subtree_dictionary:
        subtree_key = None
    
    subtree = subtree_dictionary[subtree_key]
    
    return classify(subtree, element)

In [51]:
classify(tree, {'form': 'circle', 'letter': 'C', 'color': 'green'})

False

In [52]:
classify(tree, {'form': 'octagon', 'letter': 'Z', 'color': 'chartreuse'})

True

## Build The Tree

In [56]:
def find_best_split(features, target, split_candidates):
        
    entropies = [
        entropy_on_split(features, target, feature_label)
        for feature_label in split_candidates
    ]
    
    best_index = np.argmin(entropies)
    return split_candidates[best_index]

In [57]:
def build_tree(features, target, split_candidates=None):
    if split_candidates is None:
        split_candidates = list(features.columns)
    
    total_count = target.count()
    true_count = target.sum()
    false_count = total_count - true_count
    
    if false_count == 0: return True
    if true_count == 0: return False
    
    if split_candidates == []:
        return true_count > false_count
    
    best_attribute = find_best_split(features, target, split_candidates)

    split_candidates = [split_candidate 
                        for split_candidate in split_candidates 
                        if split_candidate is not best_attribute]
    
    best_attribute_uniques = features[best_attribute].unique()
    subtree = dict()
    for best_attr_unique in best_attribute_uniques:
        feat_subset = features[features[best_attribute] == best_attr_unique]
        target_subset = target[features[best_attribute] == best_attr_unique]
        subtree[best_attr_unique] = build_tree(feat_subset, target_subset, split_candidates)
    subtree[None] = true_count > false_count

    return (best_attribute, subtree)

In [60]:
build_tree(features, target)

('form',
 {'square': False,
  'circle': ('color',
   {'red': True,
    'green': ('letter', {'B': False, 'D': True, None: False}),
    'blue': True,
    None: True}),
  'diamond': ('color',
   {'red': True, 'blue': False, 'green': True, None: True}),
  'star': True,
  None: True})

In [71]:
features = items_df.drop('letter', axis=1)
target = items_df.letter == 'A'

In [72]:
my_tree = build_tree(features, target)

In [73]:
my_tree

('color',
 {'blue': False,
  'red': ('form', {'circle': True, 'diamond': False, None: False}),
  'green': ('form',
   {'circle': False, 'square': True, 'diamond': False, None: False}),
  'silver': False,
  'purple': False,
  None: False})

In [62]:
display(classify(my_tree, {'form': 'circle', 'letter': 'C', 'color': 'red'}))
display(classify(my_tree, {'form': 'circle', 'letter': 'C', 'color': 'green'}))
display(classify(my_tree, {'form': 'octagon', 'letter': 'Z', 'color': 'chartreuse'}))

True

False

True